=encoding utf-8

=head1 NÉV

AccountedTimeInOverview - egy jegy elszámolt idejének megjelenítése a 
jegyáttekintőkben.

=head1 LEÍRÁS

Ez egy nagyon egyszerű kiegészítő, amely egy jegy elszámolt idejét jeleníti 
meg a jegyáttekintőkben (jelenleg csak a „Kis” módban).

Engedélyeznie kell az „AccountedTime” oszlopot a rendszerbeállításokon 
keresztül (például Ticket → Frontend::Agent::Ticket::ViewStatus) azoknál a 
képernyőknél, ahol elérhetőnek kell lennie.

Ez a kiegészítő esetleg összeférhetetlen lehet más kiegészítőkkel, amelyek 
megváltoztatják az áttekintőt.

=head1 HIBAKÖVETŐ ÉS KÓDTÁROLÓ

Egy hibakövető és a kódtároló a következő címen érhető el:
L<https://github.com/reneeb/otrs-AccountedTimeInOverview>

=head1 SZERZŐ ÉS LICENC

Ez a modul az AGPL 3.0 feltételei szerint licencelt.

Szerző: Renée Bäcker C<< <otrs@perl-services.de> >>

=head1 MAGYAR FORDÍTÁS

A magyar fordítást az OTRS-megoldások csapata készítette.
Copyright (C) 2016 Úr Balázs, L<http://otrs-megoldasok.hu>
